### ISSUE TITLE
login error

### ISSUE THREAD

**Issue by aqwzs** [python-webuntis/python-webuntis#34]
I'm trying out the fist example code but when logging in it always gives me the error code -8998 and "Benutzer ist vorübergehend gesperrt", here's the error log:

```
{'id': '2021-08-29 12:32:29.664166', 'error': {'code': -8998, 'message': 'Benutzer ist vorübergehend gesperrt'}, 'jsonrpc': '2.0'}
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/webuntis/utils/remote.py", line 122, in _parse_result
    return result_body[u'result']
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 13, in <module>
    s.login()
  File "/home/pi/.local/lib/python3.5/site-packages/webuntis/session.py", line 95, in login
    }, use_login_repeat=False)
  File "/home/pi/.local/lib/python3.5/site-packages/webuntis/session.py", line 118, in _request
    data = rpc_request(self.config, method, params or {})
  File "/home/pi/.local/lib/python3.5/site-packages/webuntis/utils/remote.py", line 90, in rpc_request
    return _parse_result(request_body, result_body)
  File "/home/pi/.local/lib/python3.5/site-packages/webuntis/utils/remote.py", line 124, in _parse_result
    _parse_error_code(request_body, result_body)
  File "/home/pi/.local/lib/python3.5/site-packages/webuntis/utils/remote.py", line 142, in _parse_error_code
    raise exc
webuntis.errors.RemoteError: Benutzer ist vorübergehend gesperrt
```

**Comment by AugustH** [comment]
Did you adjust the credentials?

```python
s = webuntis.Session(
        username='api',
        password='api',
        server='webuntis.grupet.at:8080',
        ...
```

You have to use your schools server ('https://SERVERNAME.webuntis.com') and your username/password. If these are correct: contact your untis-admin to enable your account.

**Comment by aqwzs** [comment]
yes I did set the credentials right, I can login just like normal into my account so it should be enabled

**Comment by aqwzs** [comment]
the previous error code is when using python 3

when I use python 2.7 I get:

```
No handlers could be found for logger "webuntis"
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    s.login()
  File "/home/pi/.local/lib/python2.7/site-packages/webuntis/session.py", line 95, in login
    }, use_login_repeat=False)
  File "/home/pi/.local/lib/python2.7/site-packages/webuntis/session.py", line 118, in _request
    data = rpc_request(self.config, method, params or {})
  File "/home/pi/.local/lib/python2.7/site-packages/webuntis/utils/remote.py", line 90, in rpc_request
    return _parse_result(request_body, result_body)
  File "/home/pi/.local/lib/python2.7/site-packages/webuntis/utils/remote.py", line 124, in _parse_result
    _parse_error_code(request_body, result_body)
  File "/home/pi/.local/lib/python2.7/site-packages/webuntis/utils/remote.py", line 142, in _parse_error_code
    raise exc
webuntis.errors.RemoteError: <exception str() failed>
```

**Comment by aqwzs** [comment]
the qr-code login & password is not the same as the "normal" login, sorry didn't notice that
