### ISSUE TITLE
webuntis/objects.py fails when room is removed

### ISSUE THREAD

**Issue by knuthfund** [python-webuntis/python-webuntis#44]
webuntis/objects.py crashes when room is removed, i.e. set to 0.

Fix in objects.py:

            id=[ro[u'id'] for ro in self._data[u'ro']]

replace by:

             id=[ro[u'id'] for ro in self._data[u'ro'] if ro[u'id'] != 0 ]

Error thrown in current code:

    'ro': [{'id': 0, 'orgid': 10}, {'id': 18, 'orgid': 52}],

Traceback (most recent call last):
  File "test3.py", line 133, in <module>
    print (" p.rooms: ", p.rooms)
  File "/home/..../.local/lib/python3.7/site-packages/webuntis/utils/misc.py", line 30, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/..../.local/lib/python3.7/site-packages/webuntis/objects.py", line 363, in rooms
    id=[ro[u'id'] for ro in self._data[u'ro']]
  File "/home/.../.local/lib/python3.7/site-packages/webuntis/objects.py", line 164, in filter
    for key, values in criterions
  File "/home/.../.local/lib/python3.7/site-packages/webuntis/objects.py", line 165, in <listcomp>
    for v in values
  File "/home/.../.local/lib/python3.7/site-packages/webuntis/objects.py", line 180, in __getitem__
    data = self._data[i]  # fails if there is no such item
IndexError: list index out of range

**Comment by AugustH** [comment]
Yes and no -- your fix solves the exception, but the _real_ problem is deeper: why is there an invalid room id. And is 0 always invalid or could it be valid, nobody knows.
I will keep this open, maybe some has an idea to fix. Maybe an "global" option or an callback..., but i don't like the idea to hide the error by ignoring it.
