### ISSUE TITLE
cant get categoryid when in ClassRegEvent

### ISSUE THREAD

**Issue by steiraa** [python-webuntis/python-webuntis#46]
When I try to run the followng code, it crashes with the following error message:

```python
strt = datetime.datetime(2022, 10, 12)
endd = datetime.datetime.now()
for reg in s.class_reg_events(start=strt, end=endd):
    print(reg.category)
````

```
Traceback (most recent call last):
  File "c:\Ikarus\Untis\test02.py", line 49, in <module>
    print(reg.category)
  File "C:\Users\ls15\AppData\Local\Programs\Python\Python310\lib\site-packages\webuntis\utils\misc.py", line 30, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "C:\Users\ls15\AppData\Local\Programs\Python\Python310\lib\site-packages\webuntis\objects.py", line 1134, in category
    id=set(self._data[u'categoryId'])
KeyError: 'categoryId'
````

**Comment by AugustH** [comment]
The problem is that Untis sometimes skips empty fields in the answer. So you will have to handle this :cry:
You could check: set a breakpoint (or print) and look at `_data` -- which is the raw data received from the server. Is the data there, maybe with another name?

Sadly all my available accounts are not allowed to do this request (trying to get that fixed in the next days).
