### ISSUE TITLE
IndexError if no room is set

### ISSUE THREAD

**Issue by Mr-Comand** [python-webuntis/python-webuntis#51]
If i try to get the rooms from a lesson with out an assigned room I get an IndexError even if I just try to get the length of the rooms array.

Traceback (most recent call last):
  File "main.py", line 84, in build_lesson
    print(len(stu.rooms))
  File "C:\Users\Name\AppData\Local\Programs\Python\Python310\lib\site-packages\webuntis\utils\misc.py", line 30, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "C:\Users\Name\AppData\Local\Programs\Python\Python310\lib\site-packages\webuntis\objects.py", line 365, in rooms
    return self._session.rooms(from_cache=True).filter(
  File "C:\Users\Name\AppData\Local\Programs\Python\Python310\lib\site-packages\webuntis\objects.py", line 163, in filter
    data=[self.filter(**{key: v})[0]
  File "C:\Users\Name\AppData\Local\Programs\Python\Python310\lib\site-packages\webuntis\objects.py", line 163, in <listcomp>
    data=[self.filter(**{key: v})[0]
  File "C:\Users\Name\AppData\Local\Programs\Python\Python310\lib\site-packages\webuntis\objects.py", line 180, in __getitem__
    data = self._data[i]  # fails if there is no such item
IndexError: list index out of range

**Comment by IceWizard7** [comment]
I have also been encountering the same issue.

Traceback (most recent call last):
  File "/PATH/untis_test.py", line 38, in <module>
    print(f'{period.rooms=}'
                ^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/webuntis/utils/misc.py", line 30, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/webuntis/objects.py", line 365, in rooms
    return self._session.rooms(from_cache=True).filter(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/webuntis/objects.py", line 163, in filter
    data=[self.filter(**{key: v})[0]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/webuntis/objects.py", line 163, in <listcomp>
    data=[self.filter(**{key: v})[0]
          ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/opt/homebrew/lib/python3.11/site-packages/webuntis/objects.py", line 180, in __getitem__
    data = self._data[i]  # fails if there is no such item
           ~~~~~~~~~~^^^
IndexError: list index out of range

The comment in the last line "fails if there is no such item" tells it, but maybe return None instead of throwing an error...?

**Comment by AugustH** [comment]
- the api delivers (or does not deliver) a lot of values, some of them are sometimes missing 
- return _None_ helps only a little, if you continue and access e.g. say _room.name_ it will break there, without the hint in the source code
