### ISSUE TITLE
Can't get a timetable

### ISSUE THREAD

**Issue by breexly** [python-webuntis/python-webuntis#55]
I'm new to python so please tell me in detail what I've done wrong :)

I wanted to get a timetable as a test. But I've got some errors. This is my code (I got the latest release):

import webuntis

s = webuntis.Session(
    server='****.webuntis.com',
    username='****',
    password='****',
    school='****',
    useragent='Test'
)

s.login()
klassen = s.klassen().filter(name="Q2")
print(klassen)
tt = s.timetable(klasse=klassen, start=1, end=2)
s.logout()

I can print out all klassen so I've got a working connection. I basically copied the code from the instructions (https://python-webuntis.readthedocs.io/en/stable/session.html#webuntis.Session.timetable) but I'm getting this error in the consol:

[Q2]

Traceback (most recent call last):
  File "/home/tim/PycharmProjects/Webuntis/Updater.py", line 14, in <module>
    tt = s.timetable(klasse=klassen, start=1, end=2)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/.local/lib/python3.11/site-packages/webuntis/utils/misc.py", line 146, in inner
    result_class, jsonrpc_method, jsonrpc_args = func(self, **kwargs)
                                                 ^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/.local/lib/python3.11/site-packages/webuntis/session.py", line 221, in timetable
    id=int(element_id), type=element_type_table[element_type])
       ^^^^^^^^^^^^^^^
  File "/home/tim/.local/lib/python3.11/site-packages/webuntis/objects.py", line 53, in __int__
    assert self.id is not None
           ^^^^^^^^^^^^^^^^^^^
AssertionError

Initially before checking the instructions I tried to get a timetable like this:
tt = s.timetable(start=1, end=2)

but that hasn't worked because "TypeError: You have to specify exactly one of the following parameters by keyword: klasse, teacher, subject, room, student"

So I think the klasse parameter is needed.

BTW: How can I get my timetable? In Untis we got student specific timetables. I can't get all students to find my student object. Is there any way to get the student object of the account logged in?

thanks in advance :)

**Comment by AugustH** [comment]
start, end should be dates, not just numbers. See the example at https://github.com/python-webuntis/python-webuntis/blob/master/examples/html_timetable.py

**Comment by breexly** [comment]
Ok. I just copied the dates from the example. still the same issue.

Code:

import webuntis
import datetime

today = datetime.date.today()
monday = today - datetime.timedelta(days=today.weekday())
friday = monday + datetime.timedelta(days=4)

s = webuntis.Session(
    server='---.webuntis.com',
    username='---',
    password='------',
    school='-------',
    useragent='Test'
)

s.login()
klassen = s.klassen().filter(name="Q2")
print(klassen)
tt = s.timetable(klasse=klassen, start=monday, end=friday)
s.logout()

Console 

[Q2]
Traceback (most recent call last):
  File "/home/tim/PycharmProjects/Webuntis/Updater.py", line 18, in <module>
    tt = s.timetable(klasse=klassen, start=monday, end=friday)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/.local/lib/python3.11/site-packages/webuntis/utils/misc.py", line 146, in inner
    result_class, jsonrpc_method, jsonrpc_args = func(self, **kwargs)
                                                 ^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/.local/lib/python3.11/site-packages/webuntis/session.py", line 221, in timetable
    id=int(element_id), type=element_type_table[element_type])
       ^^^^^^^^^^^^^^^
  File "/home/tim/.local/lib/python3.11/site-packages/webuntis/objects.py", line 53, in __int__
    assert self.id is not None
           ^^^^^^^^^^^^^^^^^^^
AssertionError

Process finished with exit code 1

**Comment by AugustH** [comment]
`filter()` returns a list, you have to access the first element

`s.klassen().filter(name='5CN')[0]`

that's why the output is [Q2] and not only Q2

**Comment by breexly** [comment]
Awesome! Thanks!
Now another question: In the last years in school one can choose their courses. Therefore each Student has an individual timetable. Every possible course for this year is for example in the Q2 timetable. This is the problem as I want to get my timetable with my courses and not every course someone my year has.

I think one need to filter by student rather than klasse. I thought one could get every student and filter by name to get my student object but sadly I don't have access to all students.

Can I somehow get my student object so i can filter for my timetable?

**Comment by breexly** [comment]
NVM. Found the getStudent method. I now got my student object (full_name is correct) and am requesting the timetable. But I got this error:

{'jsonrpc': '2.0', 'id': '2024-02-24 18:44:22.023758', 'error': {'message': 'no right for timetable', 'code': -8509}}
Traceback (most recent call last):
  File "/home/tim/.local/lib/python3.11/site-packages/webuntis/utils/remote.py", line 123, in _parse_result
    return result_body[u'result']
           ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tim/PycharmProjects/Webuntis/Updater.py", line 19, in <module>
    tt = s.timetable(student=student, start=monday, end=friday)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/.local/lib/python3.11/site-packages/webuntis/utils/misc.py", line 156, in inner
    data = self._request(jsonrpc_method, jsonrpc_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/.local/lib/python3.11/site-packages/webuntis/session.py", line 118, in _request
    data = rpc_request(self.config, method, params or {})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/.local/lib/python3.11/site-packages/webuntis/utils/remote.py", line 91, in rpc_request
    return _parse_result(request_body, result_body)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tim/.local/lib/python3.11/site-packages/webuntis/utils/remote.py", line 125, in _parse_result
    _parse_error_code(request_body, result_body)
  File "/home/tim/.local/lib/python3.11/site-packages/webuntis/utils/remote.py", line 143, in _parse_error_code
    raise exc
webuntis.errors.RemoteError: no right for timetable

I think i don't have the right to get the timetable. Can the admin allow a user or a group of users just the access to the timetable via the API and nothing else or do they need to get admins too?

**Comment by AugustH** [comment]
https://github.com/python-webuntis/python-webuntis/blob/master/docs/quickstart.rst has a list of needed rights

**Comment by breexly** [comment]
I was able to make a request for a timetable when the parameter was klasse but with the students parameter i get the error above. How can that happen?

**Comment by AugustH** [comment]
yes, i think getTimetable needs different right for different data

**Comment by breexly** [comment]
ah okay. I'll ask my IT classes teacher if he can provide me with the right to do the request. I'll be back when I have news

**Comment by breexly** [comment]
NVM. found out that I needed to add my second name :) 

another question. If I have the period object of a lesson and I return the code_colour its no colour code but the same output (None, cancelled) when returning code. What do I have to do to get the colours?

**Comment by AugustH** [comment]
the colour code seems to be optional -- only set for some periods (changes?). If it is set you get something like
```ColorInfo({'cancelled': {'foreColor': '000000', 'backColor': 'ededed'}})```
