### ISSUE TITLE
Issues when accessing period.subjects on Subjects not registered to user. 

### ISSUE THREAD

**Issue by Demohstens** [python-webuntis/python-webuntis#57]
The [subjects function](https://github.com/python-webuntis/python-webuntis/blob/470c629770656d58b47703308dcb06bc3d5accd3/webuntis/objects.py#L349) results in access to period.subjects throwing an IndexError `"data = self._data[i]  # fails if there is no such item"`. Using an Try except block to catch the error "solves" the issue. I have narrowed down the periods to two hours I have in my webuntis interface yet do not attend / are not for me. So I am assuming that they are somehow not accessible through my API credentials? 

```Traceback (most recent call last):
  File "g:\My Drive\Code\Python\Scheduler\main.py", line 56, in <module>
    get_timetable_as_html()
  File "g:\My Drive\Code\Python\Scheduler\main.py", line 44, in get_timetable_as_html
    print(unidecode(', '.join(su.name for su in period.subjects)))
                                                ^^^^^^^^^^^^^^^
  File "C:\Users\...\AppData\Local\Programs\Python\Python312\Lib\site-packages\webuntis\utils\misc.py", line 30, in __get__        
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ^^^^^^^^^^^^^^
  File "C:\Users\...\AppData\Local\Programs\Python\Python312\Lib\site-packages\webuntis\objects.py", line 355, in subjects
    return self._session.subjects(from_cache=True).filter(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\AppData\Local\Programs\Python\Python312\Lib\site-packages\webuntis\objects.py", line 163, in filter
    data=[self.filter(**{key: v})[0]
          ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "C:\Users\...\AppData\Local\Programs\Python\Python312\Lib\site-packages\webuntis\objects.py", line 180, in __getitem__      
    data = self._data[i]  # fails if there is no such item
           ~~~~~~~~~~^^^
IndexError: list index out of range```

**Comment by AugustH** [comment]
Sometimes he API delivers "bad" values: an integer values which is not valid index for the corresponding table -- best thing is do deliver an Exception.

**Comment by Demohstens** [comment]
I understand. Ignoring it works fine for me, but in general I would prefer an exception along the lines of "BadApiValues" to be thrown. This allows for more elegant handling by the user in my opinion.
